[package]
name = "pancakes"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hello-macro = { path = "../hello-macro" }
hello-macro-derive = { path = "../hello-macro/hello-macro-derive" }
